### ISSUE TITLE
Настройка автопуша

### ISSUE THREAD

**Issue by Minister-of-Shitcode** [Skirgan/TerraBot#3]
```yaml
name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Убедитесь, что у вас есть requirements.txt

      - name: Run main.py
        run: python main.py
```
